import type { Metadata } from "next";
import "./globals.scss";
import { Inter_Tight } from 'next/font/google'
import { Header } from "./components/header";


const interTight = Inter_Tight({ subsets: ['latin'], weight: ['500'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={interTight.className}>
        <Header />
        {children}
      </body>
    </html >
  );
}
